### ISSUE TITLE
Support for “Sonoff Zigbee 3.0 USB Dongle Plus V2” (model “ZBDongle-E”) ?

### ISSUE THREAD

**Issue by cryptoscuttlebutt** [nccgroup/Sniffle#100]
Are there any plans to make this project available for the new “Sonoff Zigbee 3.0 USB Dongle Plus V2” (model “ZBDongle-E”) based on Silicon Labs EFR32MG21?

https://community.home-assistant.io/t/itead-s-sonoff-zigbee-3-0-usb-dongle-plus-v2-model-zbdongle-e-based-on-silicon-labs-efr32mg21-radio-soc-mcu/442695

**Comment by sultanqasim** [comment]
No, the microcontroller in that model is completely different and incompatible with Sniffle. Only the ZBDongle-P is supported.
