### ISSUE TITLE
Removing simplelink SDK directory once sniffle built

### ISSUE THREAD

**Issue by D3vil0p3r** [nccgroup/Sniffle#104]
Once I built Sniffle by running `make` in `fw` folder, if everything is ok, can I then remove `simplelink_cc13xx_cc26xx_sdk_7_41_00_17`, `sysconfig` and `xdctools_3_62_01_15_core` directories?

Uniflash is only a build dependency or a runtime dependency for Sniffle?

**Comment by sultanqasim** [comment]
The SDK is only needed for building the firmware. It's not a runtime dependency. You don't need it if you're using prebuilt firmware or you already built the firmware yourself.

**Comment by D3vil0p3r** [comment]
> Uniflash is only a build dependency or a runtime dependency for Sniffle?
>
What about Uniflash dependency? Is it runtime or build dep?

**Comment by sultanqasim** [comment]
It’s only used for flashing the firmware. You don’t need Uniflash at runtime.

**Comment by D3vil0p3r** [comment]
So I guess we don't need at building time too...

**Comment by sultanqasim** [comment]
Correct, you don’t need Uniflash to build the firmware.
