### ISSUE TITLE
hex-file

### ISSUE THREAD

**Issue by TorstenRobitzki** [nccgroup/Sniffle#14]
Hi,
is there a prebuild hex file to simply flash the eval boards?

best regards,
Torsten

**Comment by TorstenRobitzki** [comment]
looks like the provided out-file is a elf file :-)

**Comment by sultanqasim** [comment]
Looks like you figured it out, but in case anyone else has this question, you can flash the ELF file using DSLite or Uniflash. They will parse the ELF and take care of loading the right code and data to the right location.

**Comment by TorstenRobitzki** [comment]
I first tried to simply use my JLink to flash the device. But I didn't managed to convince the JLink to work with the CC26xxx. But the TI tools worked very well.
