### ISSUE TITLE
I can't get it to install as it currently is defined.

### ISSUE THREAD

**Issue by rhyde** [nccgroup/Sniffle#18]
When I try to build it complains that I do not have jdk7 installed, and I can't get a copy with a rational license for my mac.  Can someone suggest what I need to update to make it work with a current version of openjdk?

**Comment by sultanqasim** [comment]
What part needs JDK? Some TI thing? I thought the TI bits only used node-webkit.

**Comment by rhyde** [comment]
When I type make it whines about it.  I will try to reproduce it again and post the errors

**Comment by sultanqasim** [comment]
Closing due to vague nature of issue and lack of requested information.
