### ISSUE TITLE
Installation Process

### ISSUE THREAD

**Issue by anini9519** [nccgroup/Sniffle#2]
Is there a video that I can refer to for the Installation and Configure Sniffle ? 
ps:Apart from the steps written in the readme file.

**Comment by sultanqasim** [comment]
I don't have a video of the process, though perhaps I could make one. Where are you having issues?

If you're having difficulty building the firmware, you could use the prebuilt firmware binaries here (just flash them with TI UniFlash): https://github.com/nccgroup/Sniffle/releases/tag/v1.1

For the host side Python code, you don't need to install anything beyond Python 3.5+ and PySerial.

**Comment by anini9519** [comment]
Thank you for your response.
I was trying to install the firmware and I get this output from the terminal.
It would really great if you can make a video 
<img width="683" alt="Screen Shot 2019-11-22 at 5 12 34 PM" src="https://user-images.githubusercontent.com/38827971/69464054-52bc4580-0d4b-11ea-8c99-c05e90161a2e.png">

**Comment by sultanqasim** [comment]
Looking at your image, does the path it's complaining about exist? You might need to edit this line: https://github.com/nccgroup/Sniffle/blob/master/fw/makefile#L1

If building the firmware is too much work in your setup, you can just use the prebuilt firmware I linked earlier.

**Comment by anini9519** [comment]
I was able to flash the prebuilt firmware to TI board.
Still, It would be really great if you give me steps in more elaborate way to install the firmware from scratch.
Can you give me steps how to sniff ble packets with the given command line ?
Thanks in Advance.

**Comment by sultanqasim** [comment]
Read the README.
