### ISSUE TITLE
The same Coding Indicator (S=8) for S=8 and S=2 coding schemes

### ISSUE THREAD

**Issue by homewsn** [nccgroup/Sniffle#26]
I noticed that you always use the same Coding Indicator = 0 (S=8) for S=8 and S=2 coding schemes in those pcap frames where PHY is LE Coded.
Is there a way to get an actual Coding Indicator from the sniffer hardware?

**Comment by sultanqasim** [comment]
You’re correct about this issue. There’s probably a way to get this info, I just need to look though TI docs and implement it. It’s on my todo list.

**Comment by sultanqasim** [comment]
Fixed in https://github.com/nccgroup/Sniffle/commit/56388a098426e84c04384946c24c72d67c547c17
