### ISSUE TITLE
Compatibility with LAUNCHPAD CC1350 

### ISSUE THREAD

**Issue by giowild** [nccgroup/Sniffle#28]
Are prebuilt binaries compatible with TI LAUNCHPAD CC1350 board?

https://www.ti.com/tool/LAUNCHXL-CC1350

Thanks!

**Comment by sultanqasim** [comment]
No, Sniffle is only compatible with the CC13x2/CC26x2 and not the older CCxxx2 devices. It uses a few commands specific to the newer generation and I don't have plans to backport to the previous generation MCUs. Sorry.
