### ISSUE TITLE
Q: which of the supported device are the best hardware for sniffle?

### ISSUE THREAD

**Issue by maichai** [nccgroup/Sniffle#33]
If I have the choice, which board I buy, which yoard to you recommend to use?

The LAUNCHXL-CC1352P1 or LAUNCHXL-CC1352P-4 also support 1GHz but that's not used by sniffle I guess. However, these boards or on my end the cheapest to get hands on.

**Comment by sultanqasim** [comment]
Any of the supported devices are equally good for the purposes of using Sniffle.
