### ISSUE TITLE
Is the CC2650STK supported?

### ISSUE THREAD

**Issue by jackjansen** [nccgroup/Sniffle#47]
I have a CC2650STK lying around. BLE 5.1 in stead of BLE 5.2 (as for the 2652), and only 20KB of RAM.

Is it worth trying to get Sniffle running on this board, or is that a non-starter?

**Comment by sultanqasim** [comment]
It may be possible to port the firmware to work on it, but it would require considerable work, and some of the BLE 5 radio core commands I use are missing from the CC2650 if I remember correctly.
