### ISSUE TITLE
Forcing a repairing of bluetooth devices

### ISSUE THREAD

**Issue by PowerPress** [nccgroup/Sniffle#50]
Can this or any other software you know of send a LMP message that it lost the pairing secret to force a repairing to other bluetooth devices you are trying to sniff?

**Comment by sultanqasim** [comment]
Sniffle actually does support transmitting (as a an advertiser, initiator, connection master, or connection slave), though I haven't documented that functionality. The relay attack research I published a while back was built on Sniffle's mostly undocumented transmit capabilities. While BLE doesn't use LMP, you can send link layer PDUs to reject connection startup, and then send SMP (Security Manager Protocol) messages to encourage re-pairing.

**Comment by sultanqasim** [comment]
Closing as this isn't an "issue" and LMP is not relevant to BLE.
