### ISSUE TITLE
Linux build fails due to missing sysconfig_1.13.0

### ISSUE THREAD

**Issue by cyberxml** [nccgroup/Sniffle#60]
The default install of CCS11.2.0.00007_linux-x64.tar.gz includes sysconfig_1.12.0 and the firmate build instructions fail with the following message

> make load
 make: /home/username/ti/ccs1120/ccs/utils/sysconfig_1.13.0/sysconfig_cli.sh: No such file or directory
 make: /home/username/ti/ccs1120/ccs/utils/sysconfig_1.13.0/sysconfig_cli.sh: No such file or directory
 Building DelayHopTrigger.obj
DelayHopTrigger.c:14:10: fatal error: ti_drivers_config.h: No such file or directory
   14 | #include "ti_drivers_config.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:185: DelayHopTrigger.obj] Error 1

This is fixed by manually installing sysconfg 1.13.0 into the /home/username/ti/ccs1120/ccs/utils directory
The Linux sysconfig 1.13.0 can be downloaded here
`https://www.ti.com/tool/download/SYSCONFIG/1.13.0.2553`

The Readme for the build should be updated to include these steps.

**Comment by sultanqasim** [comment]
The readme says to use SDK 6.20.00.29 which includes the right version of SysConfig. CCS packages may include a different SysConfig version.
