### ISSUE TITLE
Run sniff_receiver.py Error

### ISSUE THREAD

**Issue by TiltedChris** [nccgroup/Sniffle#62]
Hello I got a little problem maybe can someone help me? When I try to run the python scripts I always get the error **ModuleNotFoundError: No module named 'serial'**

Code Below is my make command and then run the script

ChristiansMBP4:fw christian$ make PLATFORM=CC2652R1F
Generating configuration files...
Running script...
Validating...
Generating Code (sniffle.syscfg)...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/ti_devices_config.c...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/ti_radio_config.c...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/ti_radio_config.h...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/ti_drivers_config.c...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/ti_drivers_config.h...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/ti_utils_build_linker.cmd.genlibs...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/syscfg_c.rov.xs...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/ti_utils_runtime_model.gv...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/ti_utils_runtime_Makefile...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/ti_sysbios_config.h...
Writing /Users/christian/Downloads/Sniffle-1.7/fw/ti_sysbios_config.c...
generation complete
Building /Users/christian/Downloads/Sniffle-1.7/fw/ti_devices_config.obj
Building /Users/christian/Downloads/Sniffle-1.7/fw/ti_radio_config.obj
Building /Users/christian/Downloads/Sniffle-1.7/fw/ti_drivers_config.obj
Building /Users/christian/Downloads/Sniffle-1.7/fw/ti_sysbios_config.obj
Building adv_header_cache.obj
Building AuxAdvScheduler.obj
Building base64.obj
Building CommandTask.obj
Building conf_queue.obj
Building csa2.obj
Building debug.obj
Building DelayHopTrigger.obj
Building DelayStopTrigger.obj
Building main.obj
Building messenger.obj
Building PacketTask.obj
Building RadioTask.obj
Building RadioWrapper.obj
Building rpa_resolver.obj
Building RFQueue.obj
Building sw_aes128.obj
Building TXQueue.obj
linking...
/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc_nano.a(libc_a-closer.o): in function `_close_r':
/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/src/newlib-cygwin/newlib/libc/reent/closer.c:47: warning: _close is not implemented and will always fail
/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc_nano.a(libc_a-signalr.o): in function `_getpid_r':
/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/src/newlib-cygwin/newlib/libc/reent/signalr.c:83: warning: _getpid is not implemented and will always fail
/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc_nano.a(libc_a-signalr.o): in function `_kill_r':
/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/src/newlib-cygwin/newlib/libc/reent/signalr.c:53: warning: _kill is not implemented and will always fail
/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc_nano.a(libc_a-lseekr.o): in function `_lseek_r':
/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/src/newlib-cygwin/newlib/libc/reent/lseekr.c:49: warning: _lseek is not implemented and will always fail
/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc_nano.a(libc_a-readr.o): in function `_read_r':
/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/src/newlib-cygwin/newlib/libc/reent/readr.c:49: warning: _read is not implemented and will always fail
/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc_nano.a(libc_a-writer.o): in function `_write_r':
/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/src/newlib-cygwin/newlib/libc/reent/writer.c:49: warning: _write is not implemented and will always fail
ChristiansMBP4:fw christian$ cd ..
ChristiansMBP4:Sniffle-1.7 christian$ cd python_cli/
ChristiansMBP4:python_cli christian$ ./sniff_receiver.py 
Traceback (most recent call last):
  File "/Users/christian/Downloads/Sniffle-1.7/python_cli/./sniff_receiver.py", line 9, in <module>
    from sniffle_hw import SniffleHW, BLE_ADV_AA, PacketMessage, DebugMessage, StateMessage, MeasurementMessage
  File "/Users/christian/Downloads/Sniffle-1.7/python_cli/sniffle_hw.py", line 6, in <module>
    from serial import Serial
ModuleNotFoundError: No module named 'serial'

**Comment by sultanqasim** [comment]
You need PySerial

**Comment by TiltedChris** [comment]
I already got PySerial
