### ISSUE TITLE
Question: temporary-follow support?

### ISSUE THREAD

**Issue by jsmif** [nccgroup/Sniffle#80]
Is it possible with the current firmware to follow connections, but only for e.g. 1-5 seconds, and then just stop following after that, even if there is no termination seen? My use case would just be opportunistic capture of the first few connection parameters and LL packet exchanges in a connection and then dropping back into general sniffing mode to catch any other connections etc. I.e. I don't want to follow an active connection forever. In my initial read of the code I don't think this is currently possible, but I just wanted to check before I customize the code if need be. Thank you.

**Comment by sultanqasim** [comment]
You can do this with the current firmware. Just call `SniffleHW.setup_sniffer()` with your desired settings again when you're done with the connection you're following, and it will go back to sniffing advertisements.

**Comment by mdxs** [comment]
Nice to see this question and the answer, as I might have a use case for this in the future. It may allow me to monitor the speed of setting up a connection in a QA (quality assurance) setting. Perhaps determine some differences between devices and setting/checking some expected timeframes for certain devices... hmm, too much to play with ;-)

**Comment by alphafox02** [comment]
In the case of “remote ID” being transmitted by several devices, I’m guessing due to it just being a bt5 extended/long range transmission, sniffle would just continue to sniff and not stop and just fixate on one transmission? Basically they’re all advertisements without an active connection?

**Comment by sultanqasim** [comment]
> In the case of “remote ID” being transmitted by several devices, I’m guessing due to it just being a bt5 extended/long range transmission, sniffle would just continue to sniff and not stop and just fixate on one transmission? Basically they’re all advertisements without an active connection?
> 
> edit: I understand the use case above now and wanting to follow connections a little and also see there’s support “for sniffing only advertisements and ignoring connections” which is probably what I’m doing.

Sniffle only follows connections when there is a `CONNECT_IND` PDU from some device connecting to an advertiser, and that too is only if Sniffle is not in an scanning (advertising only) mode.

**Comment by sultanqasim** [comment]
Closing as answered
