### ISSUE TITLE
Catsniffer release hex

### ISSUE THREAD

**Issue by JahazielLem** [nccgroup/Sniffle#82]
Hi!

I'm part of the development team of CatSniffer, and we appreciate your support for our board. We developed a tool called "Catnip" to upload firmware available in our repo through a script. Currently, we have added support to use the latest release of the sniffle_cc1352p7_1M.hex file. We have a question:

In the future, could the name of this file change? We have hardcoded the "sniffle_cc1352p7_1M" hex file in our tool, so we filter by this name. If this name changes in future releases, we will need to update our tool accordingly.
@sultanqasim In this commit: https://github.com/nccgroup/Sniffle/commit/7f46cedd718152cafc4d69c7ccdd29f499f00053 --
you mentioned not having a CatSniffer board. If you are interested in our board, please let me know, and we will gladly send one to you.

Thank you!

**Comment by sultanqasim** [comment]
I don't have any plans to change the file name for that build, so I think it should be fine to hard code that. If you send me a CatSniffer board to test new releases on, I'd be happy to include it among the list of officially supported devices. You can email me for contact information to send one over.
