### ISSUE TITLE
pcap storage of sent packets?

### ISSUE THREAD

**Issue by jsmif** [nccgroup/Sniffle#83]
I was able to copy over the pcap-writing code from sniff_receiver.py to a variant of initiator.py. But I'm wondering what the correct way is to wrap a packet to create something appropriate for writing to the pcap, when sending?

Currently I just use hw.cmd_transmit() like in initiator.py, but that doesn't go down a pcap-save path (and I expect it's not appropriate for saving, because it will be wrapped up into the pcap to be sent by other code). Is there perhaps a need for something new to be created (in conjunction with the firmware) to save outbound packets to the pcap as well as inbound?

**Comment by sultanqasim** [comment]
I have some private scripts that do exactly what you’re talking about (saving both transmitted and received packets to a PCAP file). I’ll share the relevant excerpts when I have a chance.

**Comment by sultanqasim** [comment]
While I can't share the full code unfortunately, here are some relevant snippets to give an idea of how I was doing it. I had a server set up to receive packets over a socket to send over BLE. In the main loop, I use select to check if anything was received from either the Sniffle hardware serial port or the socket providing packets to send. If a packet was received on either interface, I construct a DPacketMessage subclass instance for it, print it, and save it to a PCAP. For packets received from the socket interface, I also send them to the Sniffle firmware for transmitting over the air.

~~~Python
# global variable for pcap writer
pcwriter = None

def main():
    ...
    global pcwriter
    if not (args.output is None):
        pcwriter = PcapBleWriter(args.output)
    ...
    # hw is SniffleHW, conn is a server class with a socket receiving packets to send
    # the script initiates a connection to a target in a manner similar to initiator.py
    ...
    while True:
        ready, _, _ = select([hw.ser.fd, conn.sock], [], [])

        if conn.sock in ready:
            mtype, body = conn.recv_msg()
            if mtype != MessageType.PACKET:
                return
            event, = unpack('<H', body[:2])
            body = body[2:]
            llid = body[0] & 3
            pdu = body[2:]

            # construct packet object for display and PCAP
            pkt = DPacketMessage.from_body(body, True)
            pkt.ts_epoch = time()
            pkt.ts = pkt.ts_epoch - hw.decoder_state.first_epoch_time
            pkt.aa = hw.decoder_state.cur_aa
            pkt.event = event

            hw.cmd_transmit(llid, pdu, event)
            print_message(pkt, quiet)

        if hw.ser.fd in ready:
            msg = hw.recv_and_decode()
            print_message(msg, quiet)
~~~

~~~Python
def print_message(msg, quiet=False):
    if isinstance(msg, DPacketMessage):
        print_packet(msg, quiet)
    elif isinstance(msg, DebugMessage) or \
            isinstance(msg, StateMessage) or \
            isinstance(msg, MeasurementMessage):
        print(msg, end='\n\n')

def print_packet(pkt, quiet=False):
    is_not_empty = not (isinstance(pkt, LlDataContMessage) and pkt.data_length == 0)

    if not quiet or is_not_empty:
        print(pkt, end='\n\n')

    # Record the packet if PCAP writing is enabled
    if pcwriter and is_not_empty:
        pcwriter.write_packet_message(pkt)
~~~

**Comment by sultanqasim** [comment]
The event field is the `connEventCounter` field as defined in the Bluetooth Core Specification. It's not included in the PCAP. The `cmd_transmit` method of `SniffleHW` takes it as an optional third argument to facilitate some connection parameter change timing guesses in relay attack scenarios (though I haven't released the relay attack code). You can just ignore and not set the event field for PDUs you are sending (it will default to zero), and likewise omit the third (event) argument from `cmd_transmit`.

If you have a BLE data PDU you'd like to send, where the first byte is the LLID (and SN/NESN bits that will get ignored and replaced), second byte is the length, and remaining bytes are the PDU body (without the CRC at the end), you can send and save the packet something like this:

~~~Python
# Suppose we want to replay a LL_VERSION_IND PDU from a Broadcom controller
pdu = [
    0x07, # LLID 0x3, SN/NESN/MD/CP don't matter
    0x06, # Body length 6
    0x0c, # LL_VERSION_IND
    0x09, 0x0f, 0x00, 0x5e, 0x42
]

llid = pdu[0] & 3
body = pdu[2:]

# Transmit it
hw.cmd_transmit(llid, body)

# Construct packet class
pkt = DPacketMessage.from_body(body, True)
pkt.ts_epoch = time()
pkt.ts = pkt.ts_epoch - hw.decoder_state.first_epoch_time
pkt.aa = hw.decoder_state.cur_aa

# Save it to PCAP
pcwriter.write_packet_message(pkt)
~~~

**Comment by sultanqasim** [comment]
Sorry for the late response. Your issue is probably because your PCAP lacks a CONNECT_IND. Most likely Wireshark is getting confused when seeing data packets without a connection start packet. While Sniffle firmware doesn’t directly report the content of packets it sent, you can reconstruct the CONNECT_IND from the arguments to cmd_connect. I’m away from my computer at the moment, but I can share with you a code snippet that recreates and saves the transmitted CONNECT_IND.

**Comment by sultanqasim** [comment]
For reference, a `CONNECT_IND` PDU is an Advertising PDU whose body consists of `InitA`, `AdvA`, and `LLData`. `InitA` is the initiator's own MAC address (generated [here](https://github.com/nccgroup/Sniffle/blob/a9da84d4bdee49490d5bfff04df65957072810d3/python_cli/sniffle/sniffle_hw.py#L437)), `AdvA` is the target's MAC address, and `LLData` is generated [here](https://github.com/nccgroup/Sniffle/blob/a9da84d4bdee49490d5bfff04df65957072810d3/python_cli/sniffle/sniffle_hw.py#L510).

You'll need to write your own code to construct the `CONNECT_IND` PDU (and associated DPacketMessage subclass), but you have the pieces you need for building it.

**Comment by sultanqasim** [comment]
Oh, I see the problem now. There was a mistake in the code I gave you earlier for constructing a DPacketMessage, specifically the first argument to `DPacketMessage.from_body` should be the entire PDU (including the two byte header), not just the body.

**Comment by sultanqasim** [comment]
Regarding the first error, I see I broke things with 7bc300e5bc3e036662a5e062e9f2f9d6803786a4. Just revert that commit for now, I'll fix it properly when I have a chance.

Regarding the second error, convert the list `pdu` to `bytes` before passing it to `DPacketMessage.from_body`.

**Comment by sultanqasim** [comment]
Give me a moment, I'll write you an example of how to construct a `ConnectIndMessage` from a `CONNECT_IND` PDU.

**Comment by sultanqasim** [comment]
Here you go:

~~~Python
from sniffle.pcap import PcapBleWriter
from sniffle.packet_decoder import DPacketMessage
from time import time

pcwriter = PcapBleWriter("test.pcap")
t0 = time()

pdu = bytes([
    0xc5, # Ad type 0x5 (CONNECT_IND), ChSel = 0, RxAdd = 1, TxAdd = 1
    0x22, # Body length 34
    0x43, 0xa7, 0x2f, 0x3e, 0xcf, 0x4f, # InitA
    0xc0, 0x94, 0x90, 0x04, 0xf8, 0x4a, # AdvA
    0x2f, 0xb3, 0x9a, 0xaf, 0xdb, 0xaf, 0x9c, 0x03,
    0x0a, 0x00, 0x18, 0x00, 0x00, 0x00, 0x48, 0x00,
    0xff, 0xff, 0xff, 0x1f, 0x1f, 0x2a
])

# To send this (to connect to a target)
# init_random = True if (pdu[0] & 0x40) else False
# adv_random = True if (pdu[0] & 0x80) else False
# hw.cmd_setaddr(pdu[2:8], init_random)
# hw.cmd_connect(pdu[8:14], pdu[14:], adv_random)

pkt = DPacketMessage.from_body(pdu, False)
pkt.ts_epoch = time()
pkt.ts = pkt.ts_epoch - t0
pkt.aa = 0x8E89BED6

pcwriter.write_packet_message(pkt)

# LL_VERSION_IND PDU from a Broadcom controller
pdu = bytes([
    0x07, # LLID 0x3, SN/NESN/MD/CP don't matter
    0x06, # Body length 6
    0x0c, # LL_VERSION_IND
    0x09, 0x0f, 0x00, 0x5e, 0x42
])

pkt = DPacketMessage.from_body(pdu, True)
pkt.ts_epoch = time()
pkt.ts = pkt.ts_epoch - t0
pkt.aa = 0xDEADBEEF

pcwriter.write_packet_message(pkt)
~~~
