### ISSUE TITLE
Master branch works with -s /dev/ttyUSB0 but fails with -s /dev/serial/by-id/<long Sonoff name>

### ISSUE THREAD

**Issue by jsmif** [nccgroup/Sniffle#93]
Reflash Sonoff with

```
sudo python3 cc2538-bsl.py -p /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_55ca6286e3e4f4fba5d0448333fa99fc-if00-port0 --bootloader-sonoff-usb -ewv ~/Downloads/sniffle_cc1352p1_cc2652p1_1M.hex
<cut>
Writing 360448 bytes starting at address 0x00000000
Write 104 bytes at 0x00057F980
    Write done                                
Verifying by comparing CRC32 calculations.
    Verified (match: 0x26e6c6f2)
```

Run sniff_receiver as:

```
sudo python3 sniff_receiver.py -s /dev/ttyUSB0
```

That works.

Run sniff_receiver as:

```
sudo python3 sniff_receiver.py -s /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_55ca6286e3e4f4fba5d0448333fa99fc-if00-port0 
```

That just never outputs anything.

Any idea why it doesn't like the long-but-unique form? (I think this is a regression probably introduced into just the master branch, because I know I have some other system which uses the long form fine.)

**Comment by sultanqasim** [comment]
Strange, I’m not sure why that happens. Could you try a previously tagged release instead of the current master branch to see if the same thing occurs? I’m away from my computer at the moment but I can try later when I have a chance.

**Comment by sultanqasim** [comment]
Ah, that gives me a good pointer to what's happening. The [is_cp2102 function](https://github.com/nccgroup/Sniffle/blob/a9da84d4bdee49490d5bfff04df65957072810d3/python_cli/sniffle/sniffle_hw.py#L72) will return False if the supplied serial port path is not the canonical path to the dongle (i.e. `/dev/ttyUSB0`). Is `/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_55ca6286e3e4f4fba5d0448333fa99fc-if00-port0` a symlink to `/dev/ttyUSB0`? If so, I can change the code to follow symlinks.

**Comment by sultanqasim** [comment]
Try now with (with bf91946cf54d8186682f8ba6ae48179da93a351d)
